image: maven:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

# Cache and keep downloaded dependencies between CI pipelines
cache:
  key: maven-build
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - mvn compile

compile:
  stage: deploy
  script:
    - mvn install
    - cp /target/ctrlaltdefeat-1.0-SNAPSHOT.jar /public
  artifacts:
    paths:
      - public
    expire_in: 30 days

test:
  stage: test
  script:
    - mvn test

# Documentation
pages:
  stage: deploy
  script:
    - mvn javadoc:javadoc
    - cp -r target/site/apidocs/. public/
  artifacts:
    paths:
      - public
    expire_in: 1 day