image: maven:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

stages:
  - build
  - test
  - deploy
  - upload

# Cache and keep downloaded dependencies between CI pipelines
cache:
  key: maven-build
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

# Documentation
pages:
  stage: deploy
  script:
    - mvn javadoc:javadoc
    - cp -r target/site/apidocs/. public/
  artifacts:
    paths:
      - public
    expire_in: 1 day

compile:
  stage: deploy
  script:
    - mvn clean install
  artifacts:
    paths:
      - target/ctrlaltdefeat-1.0-SNAPSHOT.jar
    expire_in: 30 days

upload:
  stage: upload
  before_script:
    - export VERSION=$(grep -m1 '<version>' pom.xml | grep -oP  '(?<=>).*(?=<)')
  script:
    - echo $VERSION
    - ls
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file target/ctrlaltdefeat-1.0-SNAPSHOT.jar "${CI_API_V4_URL}/builds/szofttech-c-2024/group-12/ctrlaltdefeat/.m2/repository/org/example/ctrlaltdefeat/1.0-SNAPSHOT/ctrlaltdefeat-1.0-SNAPSHOT.jar"'
  dependencies:
    - build
